server:
  port: 9040
  host: localhost

spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:papao;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    username: sa
    initialize: true
  jpa:
    database: MYSQL
    showSql: false
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    properties.hibernate.hbm2ddl.auto: create-drop
    properties.hibernate.format_sql: true
    properties.hibernate.use_sql_comments: true

cloud:
  aws:
    credentials:
      accessKey: ENC(SFUU9jwMUO5P2XgbavbkdpAUfeZNAvBNONUxHPOZJp0=)
      secretKey: ENC(Vm1jcnhBCAoDYi72W2j8RHzZj2gvHHEDFcwaVGWPxlpQxP0e1aRU8UD0J7XBFD9sKWsU6ozd6Ig=)
    s3:
      bucket: papao-s3-bucket
    region:
      static: ap-northeast-2

logging.level:
  com.papaolabs.api: DEBUG
  org.springframework: INFO
  org.hibernate: ERROR
  org.hibernate.SQL: ERROR
  org.hibernate.type.BasicTypeRegistry: WARN

ribbon:
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 0
  ReadTimeout: 2500
  ConnectTimeout: 500

vision:
  ribbon:
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 0
    ReadTimeout: 2000
    ConnectTimeout: 500

jasypt:
  encryptor:
    password:

google:
  application:
    imageUrl: https://vision.googleapis.com/v1
    key: ENC(+JKVXiKjp29iLTGMJXd+259u2fATaTorka6KDwxUdc9IILDKnHJ/Bypm7oUmYuhV)

hostname: 13.124.142.195:9040