server:
  port: 9030

spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:papao;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    username: sa
    initialize: true
  jpa:
    database: MYSQL
    showSql: false
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    properties.hibernate.hbm2ddl.auto: create-drop
    properties.hibernate.format_sql: true
    properties.hibernate.use_sql_comments: true

openapi:
  url: http://localhost:9010

---
spring.profiles: dev

spring.datasource:
  url: 220.230.114.180
  username: papao_dev
  password: ENC(TEZjcPKw9dpWO5dgf9MmAw==)
  driverClassName: com.mysql.jdbc.Driver
  initialize: false
  connection-test-query: SELECT 1
  test-while-idle: true
  test-on-borrow: true
  validation-interval: 10000
  log-validation-errors: true
  validation-query: SELECT 1