insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (1, 417000, 1, '삽살개', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (2, 417000, 2, '코리아 트라이 하운드', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (3, 417000, 3, '풍산견', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (4, 417000, 4, '아프간 하운드', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (5, 417000, 5, '에어델 테리어', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (6, 417000, 6, '아키다', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (7, 417000, 7, '알라스칸 말라뮤트', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (8, 417000, 8, '아메리칸 아키다', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (9, 417000, 9, '아메리칸 코카 스파니엘', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (10, 417000, 10, '오스트랄리안 캐틀 독', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (11, 417000, 11, '오스트랄리안 셰퍼드 독', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (12, 417000, 12, '바셋 하운드', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (13, 417000, 13, '비글', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (14, 417000, 14, '비어디드 콜리', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (15, 417000, 15, '베들링턴 테리어', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (16, 417000, 16, '벨지안 셰퍼드 독', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (17, 417000, 17, '버니즈 마운틴 독', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (18, 417000, 18, '비숑 프리제', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (19, 417000, 19, '블랙 테리어', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (20, 417000, 20, '보더 콜리', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (21, 417000, 21, '보르조이', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (22, 417000, 22, '보스턴 테리어', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (23, 417000, 23, '부비에 데 플랑드르', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (24, 417000, 24, '복서', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (25, 417000, 25, '브리타니 스파니엘', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (26, 417000, 26, '불 테리어', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (27, 417000, 27, '불독', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (28, 417000, 28, '케인 코르소', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (29, 417000, 29, '캐니스 팬더', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (30, 417000, 30, '캐벌리어 킹 찰스 스파니엘', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (31, 417000, 31, '센트럴 아시안 오브차카', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (32, 417000, 32, '치와와', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (33, 417000, 33, '차이니즈 크레스티드 독', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (34, 417000, 34, '샤페이', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (35, 417000, 35, '차우차우', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (36, 417000, 36, '콜리', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (37, 417000, 37, '꼬똥 드 뚤레아', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (38, 417000, 38, '닥스훈트', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (39, 417000, 39, '달마시안', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (40, 417000, 40, '댄디 딘몬트 테리어', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (41, 417000, 41, '도베르만', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (42, 417000, 42, '도고 아르젠티노', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (43, 417000, 43, '도고 까니리오', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (44, 417000, 44, '잉글리쉬 코카 스파니엘', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (45, 417000, 45, '잉글리쉬 포인터', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (46, 417000, 46, '잉글리쉬 세터', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (47, 417000, 47, '잉글리쉬 스프링거 스파니엘', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (48, 417000, 48, '필라 브라질레오', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (49, 417000, 49, '플랫 코티드 리트리버', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (50, 417000, 50, '프렌치 불독', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (51, 417000, 51, '저먼 포인터', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (52, 417000, 52, '저먼 셰퍼드 독', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (53, 417000, 53, '자이언트 슈나우져', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (54, 417000, 54, '골든 리트리버', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (55, 417000, 55, '그레이트 덴', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (56, 417000, 56, '그레이 하운드', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (57, 417000, 57, '아이리쉬 세터', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (58, 417000, 58, '아이리쉬 울프 하운드', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (59, 417000, 59, '아이리쉬소프트코튼휘튼테리어', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (60, 417000, 60, '이탈리안 그레이 하운드', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (61, 417000, 61, '잭 러셀 테리어', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (62, 417000, 62, '재패니즈 스피츠', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (63, 417000, 63, '키스 훈드', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (64, 417000, 64, '케리 블루 테리어', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (65, 417000, 65, '키슈', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (66, 417000, 66, '클라인스피츠', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (67, 417000, 67, '진도견', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (68, 417000, 68, '코리안 마스티프', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (69, 417000, 69, '라브라도 리트리버', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (70, 417000, 70, '레이크랜드 테리어', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (71, 417000, 71, '라사 압소', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (72, 417000, 72, '말티즈', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (73, 417000, 73, '마스티프', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (74, 417000, 74, '미디엄 푸들', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (75, 417000, 75, '미니어쳐 불 테리어', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (76, 417000, 76, '미니어쳐 닥스훈트', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (77, 417000, 77, '미니어쳐 핀셔', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (78, 417000, 78, '미니어쳐 푸들', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (79, 417000, 79, '미니어쳐 슈나우저', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (80, 417000, 80, '미텔 스피츠', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (81, 417000, 81, '네오폴리탄 마스티프', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (82, 417000, 82, '뉴펀들랜드', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (83, 417000, 83, '노리치 테리어', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (84, 417000, 84, '올드 잉글리쉬 쉽독', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (85, 417000, 85, '빠삐용', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (86, 417000, 86, '파슨 러셀 테리어', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (87, 417000, 87, '페키니즈', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (88, 417000, 88, '팔렌', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (89, 417000, 89, '포메라니안', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (90, 417000, 90, '퍼그', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (91, 417000, 91, '풀리', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (92, 417000, 92, '피레니안 마운틴 독', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (93, 417000, 93, '래빗 닥스훈드', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (94, 417000, 94, '로트바일러', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (95, 417000, 95, '살루키', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (96, 417000, 96, '사모예드', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (97, 417000, 97, '스코티쉬 테리어', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (98, 417000, 98, '실리햄 테리어', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (99, 417000, 99, '셔틀랜드 쉽독', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (100, 417000, 100, '시바', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (101, 417000, 101, '시츄', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (102, 417000, 102, '시코쿠', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (103, 417000, 103, '시베리안 허스키', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (104, 417000, 104, '세인트 버나드', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (105, 417000, 105, '스탠다드 푸들', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (106, 417000, 106, '티베탄 마스티프', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (107, 417000, 107, '토이 푸들', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (108, 417000, 108, '웰시 코기 펨브로크', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (109, 417000, 109, '웰시 테리어', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (110, 417000, 110, '웨스트하이랜드화이트테리어', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (111, 417000, 111, '휘펫', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (112, 417000, 112, '와이어 폭스 테리어', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (113, 417000, 113, '요크셔 테리어', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (114, 417000, 114, '믹스견', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (115, 417000, 115, '기타', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (116, 422400, 116, '고양이', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (117, 429900, 117, '기타축종', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (118, 417000, 118, '그레이트 피레니즈', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (119, 417000, 119, '아메리칸 핏불 테리어', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (120, 417000, 120, '도사', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (121, 417000, 121, '롯트와일러', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (122, 417000, 122, '셰퍼드', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (123, 417000, 123, '슈나우져', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (124, 417000, 124, '스피츠', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (125, 417000, 125, '코카 스파니엘', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (126, 417000, 126, '포인터', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (127, 417000, 127, '폭스테리어', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (128, 417000, 128, '푸들', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (129, 417000, 129, '제페니즈칭', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (130, 417000, 130, '화이트리트리버', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (131, 417000, 131, '아메리칸 에스키모', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (132, 417000, 132, '스코티시 디어하운드', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (133, 417000, 133, '바센지', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (134, 417000, 134, '화이트테리어', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (135, 417000, 135, '핏불테리어', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (136, 417000, 136, '실키테리어', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (137, 417000, 137, '올드 잉글리쉬 불독', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (138, 417000, 138, '페터데일테리어', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (139, 417000, 139, '시잉프랑세즈', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (140, 417000, 140, '토이 맨체스터 테리어', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (141, 417000, 141, '코카 푸', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (142, 417000, 142, '라이카', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (143, 417000, 143, '오브차카', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (144, 417000, 144, '카이훗', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (145, 417000, 145, '코카시안오브차카', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (146, 417000, 146, '말라뮤트', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (147, 417000, 147, '플롯하운드', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (148, 417000, 148, '벨기에 테뷰런', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (149, 417000, 149, '울프독', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (150, 417000, 150, '아메리칸불리', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (151, 417000, 151, '시베리안라이카', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (152, 417000, 152, '마리노이즈', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (153, 417000, 154, '스테포드셔불테리어', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (154, 417000, 155, '동경견', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (155, 417000, 156, '제주개', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (156, 417000, 157, '벨기에 쉽독', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (157, 417000, 158, '카레리안 베어독', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (158, 417000, 159, '맨체스터테리어', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (159, 417000, 160, '아메리칸 불독', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (160, 417000, 161, '프레사까나리오', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (161, 417000, 162, '비즐라', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (162, 417000, 163, '와이마라너', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (163, 417000, 164, '벨기에 그로넨달', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (164, 417000, 165, '저먼 와이어헤어드 포인터', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (165, 417000, 166, '로디지안 리즈백 ', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (166, 417000, 167, '랫 테리어', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (167, 417000, 168, '프렌치 브리타니', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into animal_kind_tb (id, up_kind_code, kind_code, kind_name, created_date, updated_date) VALUES (168, 417000, 169, '브뤼셀그리펀', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (1, 6110000, '서울특별시', 6119999, '가정보호', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (2, 6110000, '서울특별시', 3220000, '강남구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (3, 6110000, '서울특별시', 3240000, '강동구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (4, 6110000, '서울특별시', 3080000, '강북구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (5, 6110000, '서울특별시', 3150000, '강서구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (6, 6110000, '서울특별시', 6119998, '개별사업', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (7, 6110000, '서울특별시', 3200000, '관악구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (8, 6110000, '서울특별시', 3040000, '광진구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (9, 6110000, '서울특별시', 3160000, '구로구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (10, 6110000, '서울특별시', 3170000, '금천구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (11, 6110000, '서울특별시', 3100000, '노원구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (12, 6110000, '서울특별시', 3090000, '도봉구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (13, 6110000, '서울특별시', 3050000, '동대문구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (14, 6110000, '서울특별시', 3190000, '동작구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (15, 6110000, '서울특별시', 3130000, '마포구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (16, 6110000, '서울특별시', 3120000, '서대문구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (17, 6110000, '서울특별시', 3210000, '서초구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (18, 6110000, '서울특별시', 3030000, '성동구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (19, 6110000, '서울특별시', 3070000, '성북구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (20, 6110000, '서울특별시', 3230000, '송파구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (21, 6110000, '서울특별시', 3140000, '양천구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (22, 6110000, '서울특별시', 3180000, '영등포구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (23, 6110000, '서울특별시', 3020000, '용산구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (24, 6110000, '서울특별시', 3110000, '은평구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (25, 6110000, '서울특별시', 3000000, '종로구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (26, 6110000, '서울특별시', 3010000, '중구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (27, 6110000, '서울특별시', 3060000, '중랑구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (28, 6260000, '부산광역시', 3360000, '강서구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (29, 6260000, '부산광역시', 3350000, '금정구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (30, 6260000, '부산광역시', 3400000, '기장군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (31, 6260000, '부산광역시', 3310000, '남구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (32, 6260000, '부산광역시', 3270000, '동구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (33, 6260000, '부산광역시', 3300000, '동래구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (34, 6260000, '부산광역시', 3290000, '부산진구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (35, 6260000, '부산광역시', 3320000, '북구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (36, 6260000, '부산광역시', 3390000, '사상구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (37, 6260000, '부산광역시', 3340000, '사하구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (38, 6260000, '부산광역시', 3260000, '서구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (39, 6260000, '부산광역시', 3380000, '수영구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (40, 6260000, '부산광역시', 3370000, '연제구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (41, 6260000, '부산광역시', 3280000, '영도구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (42, 6260000, '부산광역시', 3250000, '중구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (43, 6260000, '부산광역시', 3330000, '해운대구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (44, 6270000, '대구광역시', 3440000, '남구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (45, 6270000, '대구광역시', 3470000, '달서구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (46, 6270000, '대구광역시', 3480000, '달성군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (47, 6270000, '대구광역시', 3420000, '동구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (48, 6270000, '대구광역시', 3450000, '북구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (49, 6270000, '대구광역시', 3430000, '서구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (50, 6270000, '대구광역시', 3460000, '수성구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (51, 6270000, '대구광역시', 3410000, '중구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (52, 6280000, '인천광역시', 3570000, '강화군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (53, 6280000, '인천광역시', 3550000, '계양구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (54, 6280000, '인천광역시', 3510000, '남구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (55, 6280000, '인천광역시', 3530000, '남동구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (56, 6280000, '인천광역시', 3500000, '동구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (57, 6280000, '인천광역시', 3540000, '부평구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (58, 6280000, '인천광역시', 3560000, '서구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (59, 6280000, '인천광역시', 3520000, '연수구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (60, 6280000, '인천광역시', 3580000, '옹진군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (61, 6280000, '인천광역시', 3490000, '중구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (62, 6290000, '광주광역시', 3630000, '광산구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (63, 6290000, '광주광역시', 3610000, '남구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (64, 6290000, '광주광역시', 3590000, '동구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (65, 6290000, '광주광역시', 3620000, '북구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (66, 6290000, '광주광역시', 3600000, '서구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (67, 5690000, '세종특별자치시', 5690000, '세종특별자치시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (68, 6300000, '대전광역시', 3680000, '대덕구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (69, 6300000, '대전광역시', 3640000, '동구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (70, 6300000, '대전광역시', 3660000, '서구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (71, 6300000, '대전광역시', 3670000, '유성구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (72, 6300000, '대전광역시', 3650000, '중구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (73, 6310000, '울산광역시', 3700000, '남구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (74, 6310000, '울산광역시', 3710000, '동구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (75, 6310000, '울산광역시', 3720000, '북구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (76, 6310000, '울산광역시', 3730000, '울주군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (77, 6310000, '울산광역시', 3690000, '중구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (78, 6410000, '경기도', 4160000, '가평군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (79, 6410000, '경기도', 3940000, '고양시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (80, 6410000, '경기도', 3970000, '과천시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (81, 6410000, '경기도', 3900000, '광명시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (82, 6410000, '경기도', 5540000, '광주시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (83, 6410000, '경기도', 3980000, '구리시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (84, 6410000, '경기도', 4020000, '군포시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (85, 6410000, '경기도', 4090000, '김포시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (86, 6410000, '경기도', 3990000, '남양주시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (87, 6410000, '경기도', 3920000, '동두천시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (88, 6410000, '경기도', 3860000, '부천시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (89, 6410000, '경기도', 3780000, '성남시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (90, 6410000, '경기도', 3740000, '수원시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (91, 6410000, '경기도', 4010000, '시흥시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (92, 6410000, '경기도', 3930000, '안산시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (93, 6410000, '경기도', 4080000, '안성시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (94, 6410000, '경기도', 3830000, '안양시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (95, 6410000, '경기도', 5590000, '양주시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (96, 6410000, '경기도', 4170000, '양평군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (97, 6410000, '경기도', 5700000, '여주시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (98, 6410000, '경기도', 4140000, '연천군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (99, 6410000, '경기도', 4000000, '오산시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (100, 6410000, '경기도', 4050000, '용인시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (101, 6410000, '경기도', 5630000, '용인시 기흥구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (102, 6410000, '경기도', 4030000, '의왕시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (103, 6410000, '경기도', 3820000, '의정부시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (104, 6410000, '경기도', 4070000, '이천시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (105, 6410000, '경기도', 4060000, '파주시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (106, 6410000, '경기도', 3910000, '평택시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (107, 6410000, '경기도', 5600000, '포천시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (108, 6410000, '경기도', 4040000, '하남시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (109, 6410000, '경기도', 5530000, '화성시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (110, 6420000, '강원도', 4200000, '강릉시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (111, 6420000, '강원도', 4340000, '고성군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (112, 6420000, '강원도', 4210000, '동해시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (113, 6420000, '강원도', 4240000, '삼척시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (114, 6420000, '강원도', 4230000, '속초시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (115, 6420000, '강원도', 4320000, '양구군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (116, 6420000, '강원도', 4350000, '양양군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (117, 6420000, '강원도', 4270000, '영월군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (118, 6420000, '강원도', 4190000, '원주시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (119, 6420000, '강원도', 4330000, '인제군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (120, 6420000, '강원도', 4290000, '정선군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (121, 6420000, '강원도', 4300000, '철원군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (122, 6420000, '강원도', 4180000, '춘천시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (123, 6420000, '강원도', 4220000, '태백시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (124, 6420000, '강원도', 4280000, '평창군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (125, 6420000, '강원도', 4250000, '홍천군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (126, 6420000, '강원도', 4310000, '화천군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (127, 6420000, '강원도', 4260000, '횡성군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (128, 6430000, '충청북도', 4460000, '괴산군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (129, 6430000, '충청북도', 4480000, '단양군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (130, 6430000, '충청북도', 4420000, '보은군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (131, 6430000, '충청북도', 4440000, '영동군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (132, 6430000, '충청북도', 4430000, '옥천군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (133, 6430000, '충청북도', 4470000, '음성군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (134, 6430000, '충청북도', 4400000, '제천시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (135, 6430000, '충청북도', 5570000, '증평군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (136, 6430000, '충청북도', 4450000, '진천군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (137, 6430000, '충청북도', 5710000, '청주시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (138, 6430000, '충청북도', 4390000, '충주시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (139, 6440000, '충청남도', 5580000, '계룡시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (140, 6440000, '충청남도', 4500000, '공주시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (141, 6440000, '충청남도', 4550000, '금산군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (142, 6440000, '충청남도', 4540000, '논산시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (143, 6440000, '충청남도', 5680000, '당진시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (144, 6440000, '충청남도', 4510000, '보령시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (145, 6440000, '충청남도', 4570000, '부여군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (146, 6440000, '충청남도', 4530000, '서산시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (147, 6440000, '충청남도', 4580000, '서천군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (148, 6440000, '충청남도', 4520000, '아산시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (149, 6440000, '충청남도', 4560000, '연기군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (150, 6440000, '충청남도', 4610000, '예산군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (151, 6440000, '충청남도', 4490000, '천안시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (152, 6440000, '충청남도', 4590000, '청양군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (153, 6440000, '충청남도', 4620000, '태안군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (154, 6440000, '충청남도', 4600000, '홍성군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (155, 6450000, '전라북도', 4780000, '고창군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (156, 6450000, '전라북도', 4670000, '군산시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (157, 6450000, '전라북도', 4710000, '김제시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (158, 6450000, '전라북도', 4700000, '남원시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (159, 6450000, '전라북도', 4740000, '무주군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (160, 6450000, '전라북도', 4790000, '부안군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (161, 6450000, '전라북도', 4770000, '순창군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (162, 6450000, '전라북도', 4720000, '완주군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (163, 6450000, '전라북도', 4680000, '익산시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (164, 6450000, '전라북도', 4760000, '임실군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (165, 6450000, '전라북도', 4750000, '장수군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (166, 6450000, '전라북도', 4640000, '전주시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (167, 6450000, '전라북도', 4690000, '정읍시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (168, 6450000, '전라북도', 4730000, '진안군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (169, 6460000, '전라남도', 4920000, '강진군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (170, 6460000, '전라남도', 4880000, '고흥군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (171, 6460000, '전라남도', 4860000, '곡성군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (172, 6460000, '전라남도', 4840000, '광양시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (173, 6460000, '전라남도', 4870000, '구례군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (174, 6460000, '전라남도', 4830000, '나주시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (175, 6460000, '전라남도', 4850000, '담양군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (176, 6460000, '전라남도', 4800000, '목포시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (177, 6460000, '전라남도', 4950000, '무안군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (178, 6460000, '전라남도', 4890000, '보성군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (179, 6460000, '전라남도', 4820000, '순천시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (180, 6460000, '전라남도', 5010000, '신안군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (181, 6460000, '전라남도', 4810000, '여수시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (182, 6460000, '전라남도', 4970000, '영광군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (183, 6460000, '전라남도', 4940000, '영암군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (184, 6460000, '전라남도', 4990000, '완도군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (185, 6460000, '전라남도', 4980000, '장성군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (186, 6460000, '전라남도', 4910000, '장흥군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (187, 6460000, '전라남도', 5000000, '진도군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (188, 6460000, '전라남도', 4960000, '함평군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (189, 6460000, '전라남도', 4930000, '해남군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (190, 6460000, '전라남도', 4900000, '화순군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (191, 6470000, '경상북도', 5130000, '경산시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (192, 6470000, '경상북도', 5050000, '경주시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (193, 6470000, '경상북도', 5200000, '고령군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (194, 6470000, '경상북도', 5080000, '구미시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (195, 6470000, '경상북도', 5140000, '군위군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (196, 6470000, '경상북도', 5060000, '김천시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (197, 6470000, '경상북도', 5120000, '문경시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (198, 6470000, '경상북도', 5240000, '봉화군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (199, 6470000, '경상북도', 5110000, '상주시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (200, 6470000, '경상북도', 5210000, '성주군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (201, 6470000, '경상북도', 5070000, '안동시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (202, 6470000, '경상북도', 5180000, '영덕군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (203, 6470000, '경상북도', 5170000, '영양군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (204, 6470000, '경상북도', 5090000, '영주시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (205, 6470000, '경상북도', 5100000, '영천시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (206, 6470000, '경상북도', 5230000, '예천군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (207, 6470000, '경상북도', 5260000, '울릉군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (208, 6470000, '경상북도', 5250000, '울진군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (209, 6470000, '경상북도', 5150000, '의성군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (210, 6470000, '경상북도', 5190000, '청도군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (211, 6470000, '경상북도', 5160000, '청송군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (212, 6470000, '경상북도', 5220000, '칠곡군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (213, 6470000, '경상북도', 5020000, '포항시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (214, 6480000, '경상남도', 5370000, '거제시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (215, 6480000, '경상남도', 5470000, '거창군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (216, 6480000, '경상남도', 5420000, '고성군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (217, 6480000, '경상남도', 5350000, '김해시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (218, 6480000, '경상남도', 5430000, '남해군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (219, 6480000, '경상남도', 5360000, '밀양시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (220, 6480000, '경상남도', 5340000, '사천시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (221, 6480000, '경상남도', 5450000, '산청군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (222, 6480000, '경상남도', 5380000, '양산시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (223, 6480000, '경상남도', 5390000, '의령군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (224, 6480000, '경상남도', 5310000, '진주시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (225, 6480000, '경상남도', 5410000, '창녕군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (226, 6480000, '경상남도', 5280000, '창원 마산합포회원구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (227, 6480000, '경상남도', 5670000, '창원 의창성산구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (228, 6480000, '경상남도', 5320000, '창원 진해구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (229, 6480000, '경상남도', 5330000, '통영시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (230, 6480000, '경상남도', 5440000, '하동군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (231, 6480000, '경상남도', 5400000, '함안군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (232, 6480000, '경상남도', 5460000, '함양군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (233, 6480000, '경상남도', 5480000, '합천군', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (234, 6500000, '제주특별자치도', 6520000, '서귀포시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (235, 6500000, '제주특별자치도', 6510000, '제주시', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into region_tb (id, sido_code, sido_name, gungu_code, gungu_name, created_date, updated_date) VALUES (236, 6500000, '제주특별자치도', 6500000, '제주특별자치도', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

